name: Patch and Build

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyAllPatches --stacktrace
      - name: Build
        run: ./gradlew createMojmapPaperclip
      - name: Upload Folia jar
        uses: actions/upload-artifact@v4
        with:
          name: Folia-Snapshot
          path: folia-server/build/libs/folia-paperclip-1.21.8-R0.1-SNAPSHOT-mojmap.jar
      - name: Create Release
        if: github.event_name != 'pull_request'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.tag }}
          name: ${{ env.project_id_b }} - ${{ github.run_number }}
          body: |
            This release is automatically compiled by GitHub Actions
            Folia: now with command block and scoreboard support! 
            The aim of this fork is to re-enable vanilla commands, scoreboard and command blocks. The way this is accomplished is by using ConcurrentHashMap or synchronised maps, and making use of the Folia schedulers to maintain Folia's synchronisation rules, avoid race conditions and main thread safety. Note that a caveat of this is that commands may execute out of sequence (datapack functions may break or have unexpected behaviour) or the effects may be delayed to the subsequent tick, particularly if the target is located in a region other than the one of the command source.
            ### Commit Message
            ${{ env.commit_msg }}
          artifacts: folia-server/build/libs/folia-paperclip-1.21.8-R0.1-SNAPSHOT-mojmap.jar
          generateReleaseNotes: true
          prerelease: ${{ env.pre }}
          makeLatest: ${{ env.make_latest }}
          token: ${{ secrets.GITHUB_TOKEN }}
          replacesArtifacts: false

permissions: write-all
env:
  tag: build-${{ github.ref_name }}-${{ github.run_number }}
  project_id_b: Folia-command-blocks
  commit_id: ${{ github.sha }}
  commit_msg: ${{ github.event.head_commit.message }}
  pre: false
  make_latest: true
